### ISSUE TITLE
Binaries for Windows

### ISSUE THREAD

**Issue by anacrolix** [kelleyk/py3k-netifaces#1]
Can you provide an installer for Python 3.2 and 3.3? Cheers.

**Comment by kelleyk** [comment]
I don't do very much work on Windows, so yes, I'd be happy to, but it might take me a little while.  (Two weeks?  Probably more.)  If you do the legwork, I'd be thrilled to take a pull request. :)

**Comment by anacrolix** [comment]
Sorry, neither do I. I was hoping to avoid installing a C compiler and farting about in an unfamiliar environment. I saw the original author actually favours Windows. Perhaps he could attend to this with a merge? Cheers.

**Comment by kelleyk** [comment]
I did send him a cleaned-up diff via email, like he asked; not sure what his thoughts on merging it are.

**Comment by anacrolix** [comment]
I expect there is no interest in this anymore, specifically Python 3.2 or 3.3.
